excluded: # paths to ignore during linting. overridden byincluded.
- Pods
disabled_rules:
- line_length

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
shorthand_operator: warning # implicitly
